STCLI-190: Update dependencies (CVE-2021-3807)
folio-org/stripes-cli pull request #280
Opened 2022-02-18 18:24 UTC by julianladisch

Update dependencies to get fixed versions of vulnerable packages.

* ansi-regex - Regular Expression Denial of Service (ReDoS) - https://nvd.nist.gov/vuln/detail/CVE-2021-3807
* unset-value - Prototype Pollution - https://app.snyk.io/vuln/SNYK-JS-UNSETVALUE-2400660
* istanbul-reports - Reverse Tabnabbing - https://app.snyk.io/vuln/SNYK-JS-ISTANBULREPORTS-2328088
* ejs - Arbitrary Code Injection - https://app.snyk.io/vuln/SNYK-JS-EJS-1049328

2022-02-22 00:05 UTC, zburke requested changes
It's _great_ that you are keeping an eye on these deps. Unfortunately, our test coverage of stripes-cli itself must not be very good because while the PR looks clean here, I tried running tests in stripes-core, with stripes-cli configured to this branch and things never got off the ground: 
```
$ git diff
diff --git a/package.json b/package.json
index 83633cde..516bbc6b 100644
--- a/package.json
+++ b/package.json
@@ -47,7 +47,7 @@
     "@bigtest/mocha": "^0.5.1",
     "@bigtest/react": "^0.1.2",
     "@folio/eslint-config-stripes": "^6.0.0",
-    "@folio/stripes-cli": "^2.4.0",
+    "@folio/stripes-cli": "folio-org/stripes-cli#STCLI-190-update-deps",
     "@folio/stripes-components": "^10.0.0",
     "@folio/stripes-connect": "^7.0.0",
     "@folio/stripes-logger": "^1.0.0",
stripes-core(bump-8.2)*
$ yarn stripes test --coverage
yarn run v1.22.11
$ /Users/zburke/projects/folio-org/stripes-core/node_modules/.bin/stripes test --coverage
/Users/zburke/projects/folio-org/stripes-core/node_modules/@folio/stripes-cli/lib/stripes-cli.js:25
const validation = yargs.getValidationInstance();
                         ^

TypeError: yargs.getValidationInstance is not a function
    at Object.<anonymous> (/Users/zburke/projects/folio-org/stripes-core/node_modules/@folio/stripes-cli/lib/stripes-cli.js:25:26)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
```

2022-02-23 09:43 UTC, julianladisch commented
@zburke Thank you for pointing out these technical debts.

This is what I did to address them:

1. Replace `yargs.` by `yargs().`
2. Remove monkey-patch, seems to be no longer needed for recent yargs versions.
3. Invoke yargs as suggested in the yargs documentation: https://github.com/yargs/yargs
4. Removed unused argv variable.
5. Created https://issues.folio.org/browse/STCLI-191 for more test coverage.

2022-04-06 00:36 UTC, zburke approved these changes
These updates look great. Test PRs based on this branch in [ui-users](https://github.com/folio-org/ui-users/pull/2098) and [ui-inventory](https://github.com/folio-org/ui-inventory/pull/1650) were clean.

2022-04-06 02:02 UTC, merged

2022-04-07 09:45 UTC, BogdanDenis commented
@zburke getting this error when using `stripes-cli@2.6.10000089` to create workspace
```
TypeError: dev.createDirectory(...).then is not a function
    at C:\Users\Denys_Bohdan\AppData\Local\Yarn\Data\global\node_modules\@folio\stripes-cli\lib\commands\workspace.js:37:8
    at new Promise (<anonymous>)
    at Object.workspaceCommand [as handler] (C:\Users\Denys_Bohdan\AppData\Local\Yarn\Data\global\node_modules\@folio\stripes-cli\lib\commands\workspace.js:34:10)
    at C:\Users\Denys_Bohdan\AppData\Local\Yarn\Data\global\node_modules\@folio\stripes-cli\node_modules\yargs\build\index.cjs:1:9054
    at C:\Users\Denys_Bohdan\AppData\Local\Yarn\Data\global\node_modules\@folio\stripes-cli\node_modules\yargs\build\index.cjs:1:4924

```
This error pointed me to https://github.com/folio-org/stripes-cli/blob/3670748093bb1985f0a1ab6bca00d00bfdbb3f8d/lib/environment/development.js#L103 where we're using `kopy` which was updated to create a workspace directory
Probably the libraries API has changed between `v8` and `v9`