STCLI-231: Adjust finding  in webpack config in order to fix coverage
folio-org/stripes-cli pull request #326
Opened 2023-05-22 17:29 UTC by mkuklis

https://issues.folio.org/browse/STCLI-231

This was already fixed for bigtest tests in: https://github.com/folio-org/stripes-cli/pull/313

But I missed that the same functionality is used for Cypress tests.

2023-05-22 19:41 UTC, zburke requested changes
This didn't work for me in ui-courses#master. Lint complains here about `set` being imported in `lib/test/webpack-config.js` but not used. I think it needs to be moved to `lib/webpack-common.js` since that's where `enableCoverage` is, but some additional adjustments are necessary. 

Can you take another look? Thanks!

2023-05-22 20:48 UTC, mkuklis commented
@zburke sorry this was my fault. It should be all good now.

2023-05-25 17:34 UTC, zburke commented
Alas, @mkuklis, this still isn't working for me: 
```
ui-courses(master)*
$ yarn test
yarn run v1.22.19
$ stripes serve --coverage --port 3001 --okapi http://localhost:3002 & pid1=$! && env LOGCAT=startup yakbak-proxy -i -x -n & pid2=$! && wait-on http://localhost:3001 && cypress run; kill $pid1 $pid2
(startup) listening on port 3002, not proxying
Waiting for webpack to build...
TypeError: Cannot read properties of undefined (reading 'oneOf')
    at Array.enableCoverage (/Users/zburke/projects/folio-org/ui-courses/node_modules/@folio/stripes-cli/lib/webpack-common.js:94:47)
    at applyWebpackOverrides (/Users/zburke/projects/folio-org/ui-courses/node_modules/@folio/stripes-webpack/webpack/apply-webpack-overrides.js:15:30)
    at /Users/zburke/projects/folio-org/ui-courses/node_modules/@folio/stripes-webpack/webpack/serve.js:41:14
```

2023-05-25 18:40 UTC, mkuklis commented
@zburke this seems to work fine for me. I'm curious did you switch to this branch in ui-courses?

` "@folio/stripes-cli": "folio-org/stripes-cli#STCLI-231-again"`

2023-05-25 18:53 UTC, zburke commented
@mkuklis 🤦 I had an `.npmrc` pointed at production so my stripes-cli and stripes-webpack were out of sync. Sorry for the false alarm!

2023-05-25 18:53 UTC, zburke approved these changes

2023-05-25 18:56 UTC, merged